image:
  name: quay.io/buildah/stable:latest
  entrypoint: [""]

build-master:
  retry: 1
  stage: build
  variables:
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
    BUILDAH_ISOLATION: "chroot"

  script:
    - echo $CI_REGISTRY_PASSWORD buildah login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - buildah bud --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE $CI_PROJECT_DIR
    - buildah push $CI_REGISTRY_IMAGE docker://$CI_REGISTRY_IMAGE

  only:
    - master
