image:
  name: quay.io/buildah/stable:latest
  entrypoint: [""]

build-master:
  retry: 1
  stage: build
  tags: ["privileged"]
  variables:
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
    BUILDAH_ISOLATION: "rootless"

  script:
    - buildah login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - buildah bud --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE $CI_PROJECT_DIR
    - buildah push $CI_REGISTRY_IMAGE docker://$CI_REGISTRY_IMAGE

  only:
    - master
