image:
  name: gcr.io/kaniko-project/executor:v1.6.0-debug
  entrypoint: [""]
#image: docker:19.03.12-git

#services:
#  - docker:19.03.12-dind
#before_script:
#  - export DOCKER_HOST="tcp://localhost:2375"
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  retry: 1
  stage: build
#  tags:
#    - boston
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --force --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE --registry-mirror eu0.regi.kube.gmp.io
    # --registry-mirror e0.registry.gng.io
  # - docker build -t "$CI_REGISTRY_IMAGE" .
  # - docker push "$CI_REGISTRY_IMAGE"



  only:
    - master
