version: "2"
services:
  postgres:
    restart: always
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology

volumes:
  pgdata: {}
