apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres-apollos-crib
  namespace: demo
spec:
  version: "14.1-bullseye-postgis"
  storageType: Durable
  storage:
    storageClassName: "openebs-zfspv"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
  terminationPolicy: DoNotTerminate
