---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: apollos-crib
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_auth_backend_http
      - rabbitmq_mqtt

    additionalConfig: |
      auth_backends.1 = internal
      auth_backends.2 = rabbit_auth_backend_http
      auth_http.http_method   = post
      auth_http.user_path     = http://apollos-crib-hermes-svc:80/auth/user
      auth_http.vhost_path    = http://apollos-crib-hermes-svc:80/auth/vhost
      auth_http.resource_path = http://apollos-crib-hermes-svc:80/auth/resource
      auth_http.topic_path    = http://apollos-crib-hermes-svc:80/auth/topic
